pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Dockerize') {
            environment {
                IMAGE_NAME = 'my-app'
                TAG = 'latest'
            }
            steps {
                script {
                    def dockerImage = docker.build("${IMAGE_NAME}:${TAG}", '.')
                    dockerImage.push()
                }
            }
        }

        stage('Deploy') {
            environment {
                IMAGE_NAME = 'my-app'
                CONTAINER_NAME = 'my-app-container'
            }
            steps {
                sh "docker run -d --name ${CONTAINER_NAME} -p 8080:8080 ${IMAGE_NAME}"
            }
        }
    }
}
